version: '3'

services:
  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - "/usr/src/app/node_modules"
      - "./server:/usr/src/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - "/usr/src/app/node_modules"
      - "./worker:/usr/src/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - "/usr/src/app/node_modules"
      - "./client:/usr/src/app"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3050:80'